import type { PlanGenerationRequest } from "@/types/adaptivePlan";

export function buildPlanGenerationPrompt(request: PlanGenerationRequest): string {
  return [
    "你是一个保守的篮球弹跳训练计划生成器。",
    "只输出 GeneratedAdaptivePlan JSON，不要输出 Markdown、解释文字或额外字段。",
    "",
    "用户目标：basketball vertical jump。",
    `当前请求：${JSON.stringify(request, null, 2)}`,
    "",
    "必须考虑：",
    "- 当前训练反馈",
    "- Readiness 数据",
    "- 跟腱 / 髌腱疼痛状态",
    "- 篮球频率",
    "- 器械和计划约束",
    "- 右脚足弓和右膝轨迹控制",
    "- 上肢、核心和等长训练只服务篮球表现、传力、姿势和肌腱耐受",
    "",
    "安全规则：",
    "- Do not generate high-volume plyometrics.",
    "- Do not add max jumps on recovery days.",
    "- Do not override tendon pain with wearable readiness.",
    "- If Achilles or patellar pain >= 4/10, generate recovery-only or tendon-safety plan.",
    "- If Achilles stiffness or patellar tendon pain >= 3/10, do not generate French Contrast, PAP, or max jump work.",
    "- If basketball frequency is high, reduce gym impact volume.",
    "- No more than 2 high-impact days per week.",
    "- Add upper-body 1-2 times per week, balanced push and pull, without excessive soreness before basketball.",
    "- Add small core work 3-5 times per week: anti-rotation, anti-extension, anti-lateral-flexion, and carries.",
    "- Add isometrics 2-4 times per week when appropriate for tendon-friendly loading and position control.",
    "- If tendon pain is moderate, replace dynamic jumps with Spanish squat isometric, calf isometric hold, or split-squat isometric.",
    "- If hamstring soreness is high, do not include Nordic, hard RDL, sprinting, or max jumping.",
    "- If upper-body soreness is high, reduce medicine ball and heavy push/pull; lower-body can continue only if readiness is not affected.",
    "- French Contrast / Complex Training is optional high-intensity conversion work, not conditioning.",
    "- With multiple weekly basketball sessions, do not use French Contrast more than 1 time per week; prefer once every 7-10 days.",
    "- Full French Contrast is rare: at most once every 2-3 weeks, only with high readiness, good tendon status, and clean movement quality.",
    "- Do not schedule French Contrast on recovery/rest days or the day after high-impact basketball.",
    "- Testing days may use only low-volume activation, not full French Contrast.",
    "- More contrast volume is not better; every jump must be high quality and stop before fatigue changes landing mechanics.",
    "- Every training day must include warmup and activeRecovery.",
    "- Generated plan must be structured JSON only.",
    "- recovery/rest days should not be upgraded into hard days.",
    "- preserve right foot arch and right knee tracking focus.",
    "- include warmup, main, activeRecovery, optional eveningRecovery, and nutrition summary if available.",
    "- Do not include medical claims.",
    "",
    "输出格式必须匹配 GeneratedAdaptivePlan：metadata, days, globalRules, progressionRules, deloadRules, redFlags。",
    "metadata.source 必须为 backend-gpt。"
  ].join("\n");
}
